package main

import (
	"bytes"
	"encoding/json"
	"image"
	"image/color"
	"image/png"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
	"time"

	"github.com/LanternCX/zhiya/apps/server/internal/imagegen"
)

func TestIllustrationGenerationPersistsAndStaysPrivate(t *testing.T) {
	var generated bytes.Buffer
	picture := image.NewNRGBA(image.Rect(0, 0, 2, 2))
	picture.Set(0, 0, color.RGBA{R: 20, G: 120, B: 220, A: 255})
	_ = png.Encode(&generated, picture)
	var provider *httptest.Server
	releaseForest := make(chan struct{})
	provider = httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case "/services/aigc/multimodal-generation/generation":
			if r.Header.Get("X-DashScope-Async") != "" {
				t.Fatal("paid image channel does not support asynchronous calls")
			}
			var request map[string]any
			_ = json.NewDecoder(r.Body).Decode(&request)
			parameters := request["parameters"].(map[string]any)
			if parameters["size"] != "1536*864" || parameters["prompt_extend"] != false || parameters["watermark"] != false {
				t.Fatalf("unexpected generation parameters: %v", parameters)
			}
			input := request["input"].(map[string]any)
			messages := input["messages"].([]any)
			prompt := messages[0].(map[string]any)["content"].([]any)[0].(map[string]any)["text"].(string)
			if !bytes.Contains([]byte(prompt), []byte("不要出现文字")) {
				t.Fatalf("prompt does not prohibit visible text: %q", prompt)
			}
			if !strings.Contains(prompt, "不要设计成PPT") || !strings.Contains(prompt, "信息图") {
				t.Fatalf("prompt does not prohibit presentation-style artwork: %q", prompt)
			}
			if strings.Contains(prompt, "森林") {
				<-releaseForest
			}
			writeJSON(w, http.StatusOK, map[string]any{"output": map[string]any{
				"choices": []any{map[string]any{"message": map[string]any{"content": []any{map[string]any{"image": provider.URL + "/generated.png"}}}}},
			}})
		case "/generated.png":
			w.Header().Set("Content-Type", "image/png")
			_, _ = w.Write(generated.Bytes())
		default:
			http.NotFound(w, r)
		}
	}))
	defer provider.Close()

	a := setupAccountTest(t)
	a.app.images = imagegen.New(provider.URL, "qwen-image-3.0", "test-key", provider.Client())
	owner := a.register("illustration-owner@example.com")
	other := a.register("illustration-other@example.com")
	courseID, conversationID := a.createCourseConversation(owner)

	created := a.request(owner, "POST", "/courses/"+courseID+"/image-generations", map[string]any{
		"conversationId": conversationID,
		"pageId":         "water-cycle",
		"title":          "水循环",
		"description":    "用云、雨和河流解释水循环",
		"alt":            "云、雨和河流组成的水循环示意图",
	}, http.StatusAccepted)["generation"].(map[string]any)
	generationID := created["id"].(string)
	if created["status"] != "running" {
		t.Fatalf("generation did not start: %v", created)
	}

	var completed map[string]any
	for range 50 {
		completed = a.request(owner, "GET", "/courses/"+courseID+"/image-generations/"+generationID, nil, http.StatusOK)["generation"].(map[string]any)
		if completed["status"] == "complete" {
			break
		}
		time.Sleep(10 * time.Millisecond)
	}
	if completed["status"] != "complete" || completed["assetId"] != generationID {
		t.Fatalf("generation did not complete: %v", completed)
	}
	a.request(other, "GET", "/courses/"+courseID+"/image-generations/"+generationID, nil, http.StatusNotFound)

	download := a.request(owner, "GET", "/courses/"+courseID+"/illustrations/"+generationID+"/download", nil, http.StatusOK)
	res, err := owner.Get(download["url"].(string))
	if err != nil {
		t.Fatal(err)
	}
	defer res.Body.Close()
	if res.StatusCode != http.StatusOK {
		t.Fatalf("download returned %d", res.StatusCode)
	}

	cancelled := a.request(owner, "POST", "/courses/"+courseID+"/image-generations", map[string]any{
		"conversationId": conversationID,
		"pageId":         "cancelled-image",
		"title":          "不再需要的插图",
		"description":    "一片森林",
		"alt":            "森林场景",
	}, http.StatusAccepted)["generation"].(map[string]any)
	cancelledID := cancelled["id"].(string)
	a.request(owner, "DELETE", "/courses/"+courseID+"/image-generations/"+cancelledID, nil, http.StatusOK)
	close(releaseForest)
	time.Sleep(20 * time.Millisecond)
	gotCancelled := a.request(owner, "GET", "/courses/"+courseID+"/image-generations/"+cancelledID, nil, http.StatusOK)["generation"].(map[string]any)
	if gotCancelled["status"] != "cancelled" {
		t.Fatalf("cancelled generation was revived: %v", gotCancelled)
	}
}
