package client

import (
	"io"
	"net/http"
	"net/url"

	"github.com/LanternCX/zhiya/apps/server/cmd/api/transport"
	"github.com/LanternCX/zhiya/apps/server/internal/application/accounts"
	"github.com/LanternCX/zhiya/apps/server/internal/application/deliverables"
	"github.com/LanternCX/zhiya/apps/server/internal/logging"
)

func (a *application) Routes() http.Handler {
	storageURL, _ := url.Parse(a.config.Storage.PublicEndpoint)
	storageOrigin := storageURL.Scheme + "://" + storageURL.Host
	api := http.NewServeMux()
	api.HandleFunc("GET /api/classes", a.listClasses)
	api.HandleFunc("POST /api/classes", a.limitUser(60, a.createClass))
	api.HandleFunc("POST /api/classes/join", a.limitUser(60, a.joinClass))
	api.HandleFunc("GET /api/classes/{id}", a.getClass)
	api.HandleFunc("PATCH /api/classes/{id}", a.limitUser(60, a.renameClass))
	api.HandleFunc("DELETE /api/classes/{id}", a.limitUser(60, a.deleteClass))
	api.HandleFunc("POST /api/classes/{id}/leave", a.limitUser(60, a.leaveClass))
	api.HandleFunc("POST /api/classes/{id}/transfer", a.limitUser(60, a.transferClass))
	api.HandleFunc("DELETE /api/classes/{id}/members/{memberId}", a.limitUser(60, a.removeClassMember))
	api.HandleFunc("GET /api/classes/{id}/removed-members", a.removedClassMembers)
	api.HandleFunc("DELETE /api/classes/{id}/removed-members/{memberId}", a.limitUser(60, a.allowClassMember))
	api.HandleFunc("GET /api/classes/{id}/invitation", a.classInvitation)
	api.HandleFunc("POST /api/classes/{id}/invitation", a.limitUser(60, a.classInvitation))
	a.sharingRoutes(api, deliverables.New(a.models, a.objects))
	a.http().Deliverables(api, "/api", deliverables.New(a.models, a.objects), userAuthorization)
	api.HandleFunc("GET /api/agent/socket", a.agentStatusSocket)
	api.HandleFunc("GET /api/conversations", a.listConversations)
	api.HandleFunc("POST /api/agent/sessions", a.limitUser(300, a.openAgentSession))
	api.HandleFunc("GET /api/agent/sessions/{id}", a.getAgentSession)
	api.HandleFunc("POST /api/agent/sessions/{id}/commands", a.commandAgentSession)
	api.HandleFunc("GET /api/agent/sessions/{id}/socket", a.agentSocket)
	api.HandleFunc("GET /api/learning/socket", a.learningSocket)
	api.HandleFunc("POST /api/socket-ticket", a.limitUser(600, a.socketTicket))
	api.HandleFunc("GET /api/learning/model", a.modelInfo)
	api.HandleFunc("GET /api/speech/stream", a.speechStream)
	api.HandleFunc("GET /api/voice/session", a.voiceSessionHandler)
	api.HandleFunc("GET /api/code/languages", a.codeLanguages)
	api.HandleFunc("POST /api/code/runs", a.runCode)
	api.HandleFunc("GET /api/courses", a.listCourses)
	api.HandleFunc("POST /api/courses", a.createCourse)
	api.HandleFunc("GET /api/courses/{id}", a.getCourse)
	api.HandleFunc("PATCH /api/courses/{id}", a.updateCourse)
	api.HandleFunc("DELETE /api/courses/{id}", a.deleteCourse)
	api.HandleFunc("PUT /api/courses/{id}/conversation", a.saveCourseConversation)
	api.HandleFunc("PUT /api/courses/{id}/outline", a.replaceCourseOutline)
	api.HandleFunc("GET /api/courses/{id}/outline-reorganization", a.getCourseOutlineReorganization)
	api.HandleFunc("PUT /api/courses/{id}/outline-reorganizations/{reorganizationId}/assignments/{conversationId}", a.assignCourseOutlineConversation)
	api.HandleFunc("POST /api/courses/{id}/sections/{sectionId}/conversations", a.createCourseConversation)
	api.HandleFunc("DELETE /api/courses/{id}/sections/{sectionId}/conversations/{conversationId}", a.deleteCourseConversation)
	api.HandleFunc("GET /api/courses/{id}/materials", a.listCourseMaterials)
	api.HandleFunc("POST /api/courses/{id}/material-uploads", a.startCourseMaterialUpload)
	api.HandleFunc("GET /api/courses/{id}/materials/{materialId}/content", a.readCourseMaterial)
	api.HandleFunc("POST /api/courses/{id}/materials/{materialId}/parse", a.retryCourseMaterial)
	api.HandleFunc("POST /api/courses/{id}/material-uploads/{uploadId}/complete", a.completeCourseMaterialUpload)
	api.HandleFunc("GET /api/courses/{id}/materials/{materialId}/download", a.downloadCourseMaterial)
	api.HandleFunc("DELETE /api/courses/{id}/materials/{materialId}", a.deleteCourseMaterial)
	api.HandleFunc("POST /api/courses/{id}/image-generations", a.createIllustration)
	api.HandleFunc("GET /api/courses/{id}/image-generations/{generationId}", a.getIllustration)
	api.HandleFunc("DELETE /api/courses/{id}/image-generations/{generationId}", a.cancelIllustration)
	api.HandleFunc("GET /api/courses/{id}/illustrations/{assetId}/download", a.downloadIllustration)
	api.HandleFunc("GET /api/account-rules", func(w http.ResponseWriter, r *http.Request) {
		transport.WriteJSON(w, http.StatusOK, accounts.Rules())
	})
	api.HandleFunc("GET /health", func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "text/plain; charset=utf-8")
		_, _ = io.WriteString(w, "ok\n")
	})
	api.HandleFunc("POST /api/auth/register/start", a.limitIP(a.startRegistration))
	api.HandleFunc("POST /api/auth/register/complete", a.limitIP(a.completeRegistration))
	api.HandleFunc("POST /api/auth/login", a.limitIP(a.login))
	api.HandleFunc("GET /api/me", a.getProfile)
	api.HandleFunc("POST /api/auth/reset/start", a.limitIP(a.startPasswordReset))
	api.HandleFunc("POST /api/auth/reset/complete", a.limitIP(a.completePasswordReset))
	api.HandleFunc("POST /api/auth/logout", a.limitIP(a.logout))
	api.HandleFunc("POST /api/auth/logout-all", a.limitIP(a.logoutAll))
	api.HandleFunc("PUT /api/me/password", a.limitIP(a.changePassword))
	api.HandleFunc("PATCH /api/me", a.updateNickname)
	api.HandleFunc("PUT /api/me/avatar", a.updateAvatar)
	api.HandleFunc("POST /api/me/email/start", a.limitIP(a.startEmailChange))
	api.HandleFunc("POST /api/me/email/complete", a.limitIP(a.completeEmailChange))
	api.HandleFunc("DELETE /api/me", a.limitIP(a.deleteAccount))
	mux := http.NewServeMux()
	protected := a.protect(api)
	mux.Handle("/api/", protected)
	mux.Handle("/health", protected)
	mux.Handle("/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Security-Policy", "default-src 'self'; connect-src 'self' "+storageOrigin+"; img-src 'self' data: blob:; frame-src 'self' https://player.bilibili.com; frame-ancestors 'none'; form-action 'self'; base-uri 'none'")
		w.Header().Set("Referrer-Policy", "no-referrer")
		http.FileServer(http.Dir(a.config.Server.WebDir)).ServeHTTP(w, r)
	}))
	return logging.HTTPMiddleware(a.applicationLogger(), func(w http.ResponseWriter) {
		transport.WriteJSON(w, http.StatusInternalServerError, map[string]string{"error": "服务暂时不可用，请稍后重试"})
	})(mux)
}
